name: Generate README with Markscribe

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install markscribe
        run: go install github.com/charmbracelet/markscribe@latest

      - name: Generate README
        run: |
          markscribe -write README.md README.tpl
        env:
          WAKATIME_API_KEY: ${{ secrets.HACKATIME_API_KEY }}
          WAKATIME_URL: https://hackatime.hackclub.com/api/v1/

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "update readme" || exit 0
          git push